unique_ids:
  forms:
    Form1: MQNNVUDUUHOXWJEL3ZAIAIKKZ55YKILQ
  modules: {}
  server_modules: {}
  assets:
    theme.css: 3TRTDB3WFAOB7OQ3ZKXJ2IH64IDRWE77
    standard-page.html: N2WISFVJJPL2246WVNB5LNE66PKYZ6FB
